project:
  type: website

website:
  title: "fastai notes"
  # navbar:
  #   left:
  #     - href: index.qmd
  #       text: Home
  #     - about.qmd
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Pretty plots"
        contents:
          - pretty plots/corr_heatmaps.ipynb
      - section: "fastai"
        contents:
          - lessons/01_what_is_that.ipynb
      - section: "Notes"
        contents:
          - blog/create_blog.ipynb
          - blog/pda.ipynb
          - blog/devops.ipynb

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true



